### ISSUE TITLE
Setting up as docker gateway

### ISSUE THREAD

**Issue by RookieKiwi** [jsloan117/docker-openvpn-client#12]
Hey mate,
been looking for a decent openvpn client with surfshark configs, is it possible to have all other docker containers use this container as their internet gateway, if so how would i lay that out in a docker-compose ?

**Comment by jsloan117** [comment]
Hey,

You should be able to do this by setting whatever other container's network as the OpenVPN contains.

E.g `network_mode: "service:openvpn_client"`

This should help as well.

https://docs.docker.com/engine/reference/run/#network-settings

**Comment by jsloan117** [comment]
Hopefully, that helped. You can always check upstream docs [here](https://haugene.github.io/docker-transmission-openvpn/) -- their docs are much more robust than what I've done.
